#!/bin/bash

base_url="https://api.warframe.market/v2"

wfmarket_help() {
    cat <<EOF
wfmarket - Warframe Market CLI

Usage:
  wfmarket <command> [arguments]

Available commands:
  search              Search for an item interactively using fzf
  price <slug>        Show the lowest in-game selling price for an item
  volume <slug>       Show the total in-game quantity available for an item
  sell-orders <slug>  Show the cheapest sell orders for the given slug
  buy-orders <slug>   Show the most expensive buy orders for the given slug
  help                Show this help message

Examples:
  wfmarket search
  wfmarket price soma_prime_blueprint
  wfmarket volume soma_prime_blueprint

EOF
}

search_slug() {
  curl -s "$base_url/items" | jq -r '.data[] | "\(.slug)\t\(.i18n.en.name)"' | fzf --with-nth=2 --delimiter='\t' | cut -f1
}

get_info_from_slug() {
  curl -s "$base_url/item/$1" | jq -r
}

get_orders_from_slug() {
  curl -s -H "Cache-Control: no-cache" "$base_url/orders/item/$1" | jq -r
}

get_ingame_sell_from_slug() {
  get_orders_from_slug "$1" | jq -r '.data[] | select(.type == "sell")' | jq -r 'select(.user.status=="ingame")'
}

get_ingame_buy_from_slug() {
  get_orders_from_slug "$1" | jq -r '.data[] | select(.type == "buy")' | jq -r 'select(.user.status=="ingame")'
}

get_market_size_from_slug() {
  get_ingame_sell_from_slug "$1" | jq -r '.quantity' | awk '{sum+=$1} END {print sum}'
}

get_lowest_ingame_price_from_slug() {
  get_ingame_sell_from_slug "$1" | jq -r '.platinum' | sort -n | head -n1 
}

buffered_ingame_sell() {
  echo "$1" | jq -r '.data[] | select(.type == "sell")' | jq -r 'select(.user.status=="ingame")'
}

buffered_ingame_buy() {
  echo "$1" | jq -r '.data[] | select(.type == "buy")' | jq -r 'select(.user.status=="ingame")'
}

buffered_market_size() {
  buffered_ingame_sell "$1" | jq -r '.quantity' | awk '{sum+=$1} END {print sum}'
}

buffered_lowest_ingame_price() {
  buffered_ingame_sell "$1" | jq -r '.platinum' | sort -n | head -n1 
}

## Main Cli
case "$1" in
  search)
    search_slug
    ;;
  price)
    slug="$2"
    if [[ -z "$slug" ]]; then
        slug=$(search_slug)
    fi
    get_lowest_ingame_price_from_slug "$slug"
    ;;
  volume)
    slug="$2"
    if [[ -z "$slug" ]]; then
        slug=$(search_slug)
    fi
    get_market_size_from_slug "$slug"
    ;;
  info)
    slug="$2"
    if [[ -z "$slug" ]]; then
        slug=$(search_slug)
    fi
    get_info_from_slug "$slug"
    ;;
  sell-orders)
    slug="$2"
    if [[ -z "$slug" ]]; then
        slug=$(search_slug)
    fi
    orders="$(get_ingame_sell_from_slug "$slug")"
    item_name="$(get_info_from_slug "$slug"|jq -r '.data.i18n.en.name')"
    echo "Cheapest orders for $item_name"
    echo "$orders" | jq -rs '. | sort_by(.platinum) | .[0:5]' | jq -r '.[] | "\(.quantity)\t\(.platinum)p\t\(.user.ingameName)"'
    ;;
  buy-orders)
    slug="$2"
    if [[ -z "$slug" ]]; then
        slug=$(search_slug)
    fi
    orders="$(get_ingame_buy_from_slug "$slug")"
    item_name="$(get_info_from_slug "$slug"|jq -r '.data.i18n.en.name')"
    echo "Most expensive orders for $item_name"
    echo "$orders" | jq -rs '. | sort_by(.platinum) | reverse |.[0:5]' | jq -r '.[] | "\(.quantity)\t\(.platinum)p\t\(.user.ingameName)"'
    ;;
  help|"")
    wfmarket_help
    ;;
  *)
    echo "Unknown command: $1"
    echo
    wfmarket_help
    exit 1
    ;;
esac
